//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSynchro.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IServiceWCFSmart")]
    public interface IServiceWCFSmart {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/GetData", ReplyAction="http://tempuri.org/IServiceWCFSmart/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/GetData", ReplyAction="http://tempuri.org/IServiceWCFSmart/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/GetAllFilmsDBFilm", ReplyAction="http://tempuri.org/IServiceWCFSmart/GetAllFilmsDBFilmResponse")]
        DTOLibrary.FilmDTO[] GetAllFilmsDBFilm();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/GetAllFilmsDBFilm", ReplyAction="http://tempuri.org/IServiceWCFSmart/GetAllFilmsDBFilmResponse")]
        System.Threading.Tasks.Task<DTOLibrary.FilmDTO[]> GetAllFilmsDBFilmAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/GetFilmsPage", ReplyAction="http://tempuri.org/IServiceWCFSmart/GetFilmsPageResponse")]
        DTOLibrary.FilmDTO[] GetFilmsPage(int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/GetFilmsPage", ReplyAction="http://tempuri.org/IServiceWCFSmart/GetFilmsPageResponse")]
        System.Threading.Tasks.Task<DTOLibrary.FilmDTO[]> GetFilmsPageAsync(int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/ReserveFilm", ReplyAction="http://tempuri.org/IServiceWCFSmart/ReserveFilmResponse")]
        bool ReserveFilm(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/ReserveFilm", ReplyAction="http://tempuri.org/IServiceWCFSmart/ReserveFilmResponse")]
        System.Threading.Tasks.Task<bool> ReserveFilmAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/GetFilmInfo", ReplyAction="http://tempuri.org/IServiceWCFSmart/GetFilmInfoResponse")]
        DTOLibrary.FilmDTO GetFilmInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/GetFilmInfo", ReplyAction="http://tempuri.org/IServiceWCFSmart/GetFilmInfoResponse")]
        System.Threading.Tasks.Task<DTOLibrary.FilmDTO> GetFilmInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/RetourFilm", ReplyAction="http://tempuri.org/IServiceWCFSmart/RetourFilmResponse")]
        bool RetourFilm(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmart/RetourFilm", ReplyAction="http://tempuri.org/IServiceWCFSmart/RetourFilmResponse")]
        System.Threading.Tasks.Task<bool> RetourFilmAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWCFSmartChannel : SmartSynchro.ServiceReference.IServiceWCFSmart, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWCFSmartClient : System.ServiceModel.ClientBase<SmartSynchro.ServiceReference.IServiceWCFSmart>, SmartSynchro.ServiceReference.IServiceWCFSmart {
        
        public ServiceWCFSmartClient() {
        }
        
        public ServiceWCFSmartClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWCFSmartClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFSmartClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFSmartClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public DTOLibrary.FilmDTO[] GetAllFilmsDBFilm() {
            return base.Channel.GetAllFilmsDBFilm();
        }
        
        public System.Threading.Tasks.Task<DTOLibrary.FilmDTO[]> GetAllFilmsDBFilmAsync() {
            return base.Channel.GetAllFilmsDBFilmAsync();
        }
        
        public DTOLibrary.FilmDTO[] GetFilmsPage(int page) {
            return base.Channel.GetFilmsPage(page);
        }
        
        public System.Threading.Tasks.Task<DTOLibrary.FilmDTO[]> GetFilmsPageAsync(int page) {
            return base.Channel.GetFilmsPageAsync(page);
        }
        
        public bool ReserveFilm(int id) {
            return base.Channel.ReserveFilm(id);
        }
        
        public System.Threading.Tasks.Task<bool> ReserveFilmAsync(int id) {
            return base.Channel.ReserveFilmAsync(id);
        }
        
        public DTOLibrary.FilmDTO GetFilmInfo(int id) {
            return base.Channel.GetFilmInfo(id);
        }
        
        public System.Threading.Tasks.Task<DTOLibrary.FilmDTO> GetFilmInfoAsync(int id) {
            return base.Channel.GetFilmInfoAsync(id);
        }
        
        public bool RetourFilm(int id) {
            return base.Channel.RetourFilm(id);
        }
        
        public System.Threading.Tasks.Task<bool> RetourFilmAsync(int id) {
            return base.Channel.RetourFilmAsync(id);
        }
    }
}
